# Generated by Django 3.1.4 on 2021-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
