# Generated by Django 3.1.4 on 2021-01-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_id', models.PositiveIntegerField(unique=True)),
                ('sem', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('credit', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='IAmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.PositiveIntegerField()),
                ('test2', models.PositiveIntegerField()),
                ('test3', models.PositiveIntegerField()),
                ('final_marks', models.PositiveIntegerField()),
                ('ss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student')),
            ],
        ),
    ]
