# Generated by Django 3.1.4 on 2021-01-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210117_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iamarks',
            name='final_marks',
        ),
        migrations.AddField(
            model_name='iamarks',
            name='assignment',
            field=models.PositiveIntegerField(default=0, verbose_name='Assignment'),
        ),
        migrations.AddField(
            model_name='iamarks',
            name='average_marks',
            field=models.PositiveIntegerField(default=0, verbose_name='Average'),
        ),
        migrations.AddField(
            model_name='iamarks',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='ss_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec', verbose_name='Student id'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject', verbose_name='Subject code'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='test1',
            field=models.PositiveIntegerField(default=0, verbose_name='IA 1'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='test2',
            field=models.PositiveIntegerField(default=0, verbose_name='IA 2'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='test3',
            field=models.PositiveIntegerField(default=0, verbose_name='IA 3'),
        ),
        migrations.AlterField(
            model_name='iamarks',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='Name'),
        ),
    ]
