# Generated by Django 3.1.4 on 2021-01-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210117_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iamarks',
            unique_together={('usn', 'sub_code')},
        ),
    ]
