# Generated by Django 3.1.4 on 2021-01-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210117_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamarks',
            name='finial_marks',
            field=models.PositiveIntegerField(default=0, verbose_name='Finial'),
        ),
    ]
