# Generated by Django 3.1.4 on 2021-01-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_iamarks_finial_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('AI/ML', 'AI/ML'), ('CSE', 'CSE'), ('CyberSecurity', 'CyberSecurity'), ('Networking', 'Networking'), ('Languages', 'Languages'), ('DBMS', 'DBMS'), ('Management', 'Management'), ('Basic Science', 'Basic Science'), ('Physical Edu', 'Physical Edu'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='IAmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.PositiveIntegerField(default=0, verbose_name='IA 1')),
                ('test2', models.PositiveIntegerField(default=0, verbose_name='IA 2')),
                ('test3', models.PositiveIntegerField(default=0, verbose_name='IA 3')),
                ('assignment', models.PositiveIntegerField(default=0, verbose_name='Assignment')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('average_marks', models.PositiveIntegerField(default=0, verbose_name='Average')),
                ('finial_marks', models.PositiveIntegerField(default=0, verbose_name='Finial')),
            ],
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_cordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_cord', to='management.faculty')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='iamarks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='iamarks',
            name='ss_id',
        ),
        migrations.RemoveField(
            model_name='iamarks',
            name='sub_code',
        ),
        migrations.RemoveField(
            model_name='iamarks',
            name='usn',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['usn']},
        ),
        migrations.RemoveField(
            model_name='semsec',
            name='ss_id',
        ),
        migrations.AddField(
            model_name='semsec',
            name='usn',
            field=models.ManyToManyField(to='management.Student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], on_delete=django.db.models.deletion.CASCADE, to='management.semsec', verbose_name='Sem'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='IAmarks',
        ),
        migrations.AddField(
            model_name='incharge',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='cr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.student'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='sem_cordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sem_cord', to='management.faculty'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='ss_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec', verbose_name='Sem & Sec'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject', verbose_name='Subject code'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student', verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='iamark',
            unique_together={('usn', 'sub_code')},
        ),
    ]
