# Generated by Django 3.1.4 on 2021-01-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20210121_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iamark',
            name='ss_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semsec', verbose_name='Sem'),
        ),
    ]
