# Generated by Django 3.1.4 on 2021-01-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20210121_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='cr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr2', to='management.student'),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='cr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr1', to='management.student'),
        ),
    ]
