# Generated by Django 3.1.4 on 2021-01-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210121_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamark',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.semsec', verbose_name='Semister'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Fid',
            field=models.CharField(max_length=10, verbose_name='Faculty ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(choices=[('AI/ML', 'AI/ML'), ('CSE', 'CSE'), ('CyberSecurity', 'CyberSecurity'), ('Networking', 'Networking'), ('Languages', 'Languages'), ('DBMS', 'DBMS'), ('Management', 'Management'), ('Basic Science', 'Basic Science'), ('Physical Edu', 'Physical Edu'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=25, verbose_name='Specilised in '),
        ),
        migrations.AlterUniqueTogether(
            name='semsec',
            unique_together={('sem', 'section')},
        ),
    ]
