# Generated by Django 3.1.4 on 2021-02-02 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210124_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incharge',
            name='cr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr1', to='management.student', verbose_name='CR 1'),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='cr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr2', to='management.student', verbose_name='CR 2'),
        ),
    ]
