# Generated by Django 3.1.4 on 2021-02-02 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20210202_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.PositiveIntegerField(default=0, verbose_name='IA 1')),
                ('test2', models.PositiveIntegerField(default=0, verbose_name='IA 2')),
                ('test3', models.PositiveIntegerField(default=0, verbose_name='IA 3')),
            ],
        ),
        migrations.RemoveField(
            model_name='iamark',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='iamark',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='iamark',
            name='test3',
        ),
        migrations.AddField(
            model_name='iamark',
            name='a1',
            field=models.PositiveIntegerField(default=0, verbose_name='1a'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='a2',
            field=models.PositiveIntegerField(default=0, verbose_name='1b'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='a3',
            field=models.PositiveIntegerField(default=0, verbose_name='1c'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='b1',
            field=models.PositiveIntegerField(default=0, verbose_name='2a'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='b2',
            field=models.PositiveIntegerField(default=0, verbose_name='2b'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='b3',
            field=models.PositiveIntegerField(default=0, verbose_name='2c'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='c1',
            field=models.PositiveIntegerField(default=0, verbose_name='3a'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='c2',
            field=models.PositiveIntegerField(default=0, verbose_name='3b'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='c3',
            field=models.PositiveIntegerField(default=0, verbose_name='3c'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='d1',
            field=models.PositiveIntegerField(default=0, verbose_name='4a'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='d2',
            field=models.PositiveIntegerField(default=0, verbose_name='4b'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='d3',
            field=models.PositiveIntegerField(default=0, verbose_name='4c'),
        ),
        migrations.AddField(
            model_name='iamark',
            name='internals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.internals', verbose_name='Internals'),
            preserve_default=False,
        ),
    ]
