# Generated by Django 3.1.4 on 2021-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20210202_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamark',
            name='internals',
            field=models.CharField(choices=[('IA1', 'IA1'), ('IA2', 'IA2'), ('IA3', 'IA3')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Internals',
        ),
    ]
