# Generated by Django 3.1.4 on 2021-02-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20210202_0447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iamark',
            unique_together={('usn', 'sub_code', 'internals')},
        ),
    ]
