# Generated by Django 3.1.4 on 2021-02-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20210202_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semsec',
            name='sem',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semsec',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='semsec',
            name='section',
        ),
    ]
