# Generated by Django 3.1.4 on 2021-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20210202_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamark',
            name='ispresent',
            field=models.BooleanField(default=True, verbose_name='Present / Absent'),
        ),
    ]
