# Generated by Django 3.1.4 on 2021-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_iamark_ispresent'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subject',
            field=models.ManyToManyField(to='management.Subject', verbose_name='Subject'),
        ),
    ]
